### ISSUE TITLE
2011 tests fail

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/RotamerConvolveMD#25]
The tests related to the 2011 library fail. (The tests for the 2015 library #24 all pass.)

When I run the 2011 tests
```
./test_mtssl_2011.sh
./test_mtssl_pre_2011.sh
```
I get failures (see below). Do these test pass for you, @katrinr ?

### result mtssl_2011
```
(mda_develop) yngvi:example oliver$ sdiff reference_NO_2011/peptso-xrd-47-330.dat dat/peptso-xrd-47-330.dat | less
(mda_develop) yngvi:example oliver$ ./test_mtssl_2011.sh
MDAnalysis  : INFO     MDAnalysis 0.17.0-dev STARTED logging to 'MDAnalysis.log'
MDAnalysis.app: INFO     Rotamer Convolve MD, release 1.3.0.dev --- Copyright (c) Philip W Fowler, Oliver Beckstein 2011-2013 and see AUTHORS
MDAnalysis.app: INFO     Released under the GNU Public Licence, version 2 (or higher)
MDAnalysis.app: INFO     Please cite: LS Stelzl, PW Fowler, MSP Sansom, O Beckstein. J Mol Biol 426 (2014), 735-751, doi:10.1016/j.jmb.2013.10.024
MDAnalysis.app: INFO     Loading trajectory data as Universe(peptso.gro)
MDAnalysis.app: INFO     Using rotamer library 'MTSSL 298K 2011' by Gunnar Jeschke
MDAnalysis.app: INFO     Please cite: Polyhach Y, Bordignon E, Jeschke G. Phys Chem Chem Phys. 2011; 13(6):2356-2366. doi: 10.1039/c0cp01865a
MDAnalysis.app: INFO     Starting rotamer distance analysis of trajectory peptso.gro...
MDAnalysis.app: INFO     clashDistance = 2.2 A; rotamer library = 'MTSSL 298K 2011'
Step     1/1 [100.0%]
MDAnalysis.app: INFO     Distance distribution for residues 47 - 330 was written to dat/peptso-xrd-47-330.dat
MDAnalysis.app: INFO     DONE with analysis, elapsed time      7 s
MDAnalysis.app: INFO     Plotted distance distribution to dat/peptso-xrd.pdf
MDAnalysis  : INFO     MDAnalysis STOPPED logging
13,40c13,40
<  12.50 1.035e-04
<  13.50 1.994e-04
<  14.50 6.309e-05
<  15.50 7.709e-04
<  16.50 9.198e-04
<  17.50 2.554e-03
<  18.50 6.332e-03
<  19.50 6.144e-03
<  20.50 6.524e-03
<  21.50 8.692e-03
<  22.50 2.094e-02
<  23.50 3.841e-02
<  24.50 3.635e-02
<  25.50 5.834e-02
<  26.50 4.457e-02
<  27.50 4.932e-02
<  28.50 8.508e-02
<  29.50 7.847e-02
<  30.50 1.025e-01
<  31.50 9.241e-02
<  32.50 7.836e-02
<  33.50 6.997e-02
<  34.50 7.196e-02
<  35.50 5.205e-02
<  36.50 6.082e-02
<  37.50 1.370e-02
<  38.50 1.378e-02
<  39.50 6.595e-04
---
>  12.50 4.202e-05
>  13.50 1.319e-04
>  14.50 3.261e-04
>  15.50 7.986e-04
>  16.50 1.910e-03
>  17.50 5.065e-03
>  18.50 1.146e-02
>  19.50 1.749e-02
>  20.50 2.432e-02
>  21.50 2.748e-02
>  22.50 3.441e-02
>  23.50 4.393e-02
>  24.50 5.196e-02
>  25.50 5.953e-02
>  26.50 6.635e-02
>  27.50 6.311e-02
>  28.50 7.038e-02
>  29.50 6.279e-02
>  30.50 7.267e-02
>  31.50 6.779e-02
>  32.50 6.513e-02
>  33.50 5.777e-02
>  34.50 5.508e-02
>  35.50 5.055e-02
>  36.50 4.349e-02
>  37.50 2.766e-02
>  38.50 1.613e-02
>  39.50 2.267e-03
Test FAILED.
```

### result 2011 pre
```
(mda_develop) yngvi:example oliver$ test_mtssl_pre_2011.sh
MDAnalysis  : INFO     MDAnalysis 0.17.0-dev STARTED logging to 'MDAnalysis.log'
MDAnalysis.app: INFO     Rotamer Convolve MD, release 1.3.0.dev --- Copyright (c) Philip W Fowler, Oliver Beckstein 2011-2013 and see AUTHORS
MDAnalysis.app: INFO     Released under the GNU Public Licence, version 2 (or higher)
MDAnalysis.app: INFO     Please cite: LS Stelzl, PW Fowler, MSP Sansom, O Beckstein. J Mol Biol 426 (2014), 735-751, doi:10.1016/j.jmb.2013.10.024
MDAnalysis.app: INFO     Loading trajectory data as Universe(peptso.gro)
MDAnalysis.app: INFO     Using rotamer library 'MTSSL 298K 2011' by Gunnar Jeschke
MDAnalysis.app: INFO     Please cite: Polyhach Y, Bordignon E, Jeschke G. Phys Chem Chem Phys. 2011; 13(6):2356-2366. doi: 10.1039/c0cp01865a
MDAnalysis.app: INFO     Starting rotamer distance analysis of trajectory peptso.gro...
MDAnalysis.app: INFO     clashDistance = 2.2 A; rotamer library = 'MTSSL 298K 2011'
Step     1/1 [100.0%]
MDAnalysis.app: INFO     DONE with analysis, elapsed time     17 s
MDAnalysis.app: INFO     Plotted min and max distances to dat/peptso-xrd-47.pdf
MDAnalysis  : INFO     MDAnalysis STOPPED logging
25056a25057,25520
> 14	54.0253887177
> 16	50.344865799
> 17	48.550157547
> 18	47.3681335449
> 19	46.0194034576
> 20	44.143163681
> 21	42.6607322693
> 22	41.2970142365
> 23	39.3709278107
> 24	38.0200042725
> 25	36.6918926239
> 26	34.7600078583
> 27	32.7702407837
> 28	31.795797348
> 29	31.0794448853
> 30	29.3065061569
> 31	27.2391653061
> 32	26.1878700256
> 33	25.1656360626
> 34	23.0137844086
> 35	21.5190877914
> 36	19.4739847183
> 38	16.8087253571
> 39	14.9752435684
> 40	13.04839468
> 41	11.9466691017
> 42	12.2272953987
> 43	9.22561788559
> 44	8.31736469269
> 45	7.86976456642
> 46	7.07782888412
> 47	7.0127196312
> 49	9.21728944778
> 50	11.3290605545
> 51	10.7139306068
> 52	9.86572504044
> 53	12.0545711517
> 54	13.1763553619
> 55	12.9168972969
> 56	13.2134952545
> 57	15.7237286568
> 58	17.1700162888
> 59	17.3791389465
> 60	18.6662788391
> 61	21.0699357986
> 62	22.2185668945
> 63	23.2451133728
> 64	25.1440544128
> 65	26.9205799103
> 66	28.3558168411
> 67	29.8385953903
> 68	31.8399753571
> 69	32.9218711853
> 70	34.1585445404
> 72	38.8910522461
> 73	39.0991096497
> 74	39.7968902588
> 75	42.3847942352
> 76	43.4957504272
> 77	43.5393981934
> 78	44.7510433197
> 79	47.4283542633
> 80	48.4304008484
> 81	48.2668209076
> 82	47.3549957275
> 83	48.9941692352
> 84	50.2516460419
> 85	49.4024009705
> 86	48.0216350555
> 87	45.6592445374
> 88	44.0214195251
> 89	43.6097888947
> 90	42.3741645813
> 91	39.9562511444
> 92	38.8980808258
> 93	38.2885017395
> 94	36.2070980072
> 95	34.5198307037
> 96	34.025182724
> 97	32.8967056274
> 98	30.6758909225
> 99	29.1340255737
> 100	29.0434017181
> 101	27.5819091797
> 102	25.1333665848
> 103	24.7295017242
> 104	24.6635379791
> 105	23.1155195236
> 106	19.2641239166
> 107	17.1492929459
> 108	17.4401102066
> 109	16.2052617073
> 110	18.090098381
> 111	19.5281963348
> 112	18.8156328201
> 113	19.6129331589
> 114	22.1924619675
> 115	23.2171173096
> 116	23.1526899338
> 117	24.9081230164
> 118	27.3084068298
> 119	27.9050474167
> 120	28.3212919235
> 121	30.7588663101
> 122	32.3025798798
> 123	32.5372924805
> 124	33.9531860352
> 125	36.4776973724
> 126	38.1782798767
> 127	38.172876358
> 129	42.4342651367
> 130	43.1189002991
> 131	44.2772045135
> 132	46.6666374207
> 133	47.811756134
> 134	48.7188968658
> 135	50.840467453
> 136	52.6365222931
> 137	53.3418560028
> 138	55.9360485077
> 139	60.1671657562
> 140	62.0257568359
> 141	62.1850814819
> 142	59.3625888824
> 143	59.2550849915
> 144	59.9230175018
> 145	57.6470546722
> 146	56.0088310242
> 147	55.2494506836
> 148	54.1964225769
> 149	52.0250473022
> 150	50.3506069183
> 151	49.6729183197
> 152	48.3854198456
> 153	46.179397583
> 154	44.5141220093
> 155	44.0503482819
> 156	42.3604850769
> 157	40.018491745
> 158	39.5295734406
> 159	39.2551422119
> 160	37.03358078
> 161	35.0440254211
> 162	35.2676677704
> 163	34.2515468597
> 164	31.8870687485
> 165	31.1182327271
> 166	32.0819587708
> 167	30.7446269989
> 168	29.2697973251
> 170	26.4887084961
> 171	26.1036329269
> 172	23.4440889359
> 173	22.3185243607
> 174	23.7733736038
> 175	24.5350046158
> 176	24.4674129486
> 177	20.1651535034
> 178	22.4958324432
> 179	24.1783466339
> 180	24.6554756165
> 181	23.8441896439
> 182	25.6792087555
> 183	27.9542379379
> 185	29.2895946503
> 186	31.2867136002
> 187	33.0791759491
> 188	33.7416419983
> 189	35.2024307251
> 190	37.2863750458
> 191	38.3806991577
> 192	39.3795509338
> 193	41.4960441589
> 194	43.2837219238
> 195	44.1602325439
> 196	45.5035610199
> 197	47.4705410004
> 198	48.5981712341
> 199	50.7090797424
> 200	53.0050849915
> 201	53.8777599335
> 202	55.0636997223
> 203	53.4840602875
> 204	55.8139247894
> 205	54.0134277344
> 208	57.9586429596
> 210	62.1346435547
> 211	63.2317295074
> 213	64.536441803
> 214	63.969581604
> 215	63.4257850647
> 216	59.3980312347
> 218	56.9518299103
> 219	60.2094173431
> 220	58.4846572876
> 221	62.3308429718
> 222	63.4860572815
> 223	66.3375968933
> 224	68.473285675
> 225	71.6882476807
> 226	71.4775276184
> 227	68.6943092346
> 228	70.604763031
> 229	69.4983253479
> 230	67.9986572266
> 231	66.1865463257
> 232	64.7217903137
> 233	63.3163471222
> 234	61.7783203125
> 235	60.1273860931
> 236	58.4274024963
> 237	56.6133499146
> 238	55.2452926636
> 239	53.8391437531
> 240	52.0899677277
> 241	50.5693130493
> 242	49.10795784
> 243	47.2518215179
> 244	45.1204204559
> 245	43.8706588745
> 246	42.4447784424
> 247	40.0104942322
> 248	38.2828407288
> 249	37.7560920715
> 250	35.9642505646
> 251	33.8899116516
> 252	32.7620697021
> 254	28.9465103149
> 255	26.901720047
> 256	25.415186882
> 257	23.1765642166
> 258	23.6796178818
> 259	24.2088594437
> 260	26.3435955048
> 261	28.51866436
> 262	29.1629209518
> 263	30.0622797012
> 264	32.2862033844
> 265	34.2088356018
> 266	34.5623664856
> 267	35.5368671417
> 268	38.064617157
> 269	39.2205696106
> 270	39.3466815948
> 271	41.4233551025
> 272	43.1999797821
> 273	44.5680389404
> 274	46.4446773529
> 275	47.3786125183
> 276	48.1717624664
> 277	49.9088115692
> 278	51.9840278625
> 279	52.8072719574
> 280	54.0782794952
> 281	56.2611637115
> 282	57.8949337006
> 283	58.5999927521
> 284	60.8503475189
> 285	62.7703418732
> 286	66.8500556946
> 287	64.5080947876
> 289	66.7401771545
> 290	64.1882839203
> 291	64.531578064
> 292	62.538230896
> 293	61.9122238159
> 294	59.8428287506
> 295	57.7205295563
> 296	56.6597824097
> 297	56.0056419373
> 298	54.3388271332
> 299	51.8829612732
> 300	51.5121421814
> 301	50.8645362854
> 302	48.5134010315
> 303	47.0930271149
> 304	46.6891555786
> 305	44.8401908875
> 306	42.5272884369
> 307	41.8710079193
> 308	41.0542106628
> 309	38.8903942108
> 311	36.1511993408
> 312	35.3930625916
> 313	32.8941936493
> 314	31.6203136444
> 315	31.3354244232
> 316	29.4283046722
> 317	27.385931015
> 318	27.0734186172
> 319	25.4894542694
> 320	22.9773931503
> 321	22.4935789108
> 322	23.4986028671
> 323	21.7029533386
> 324	19.5601463318
> 325	20.6259975433
> 326	21.2351169586
> 327	18.9990854263
> 328	18.2472028732
> 329	20.3621225357
> 330	23.143778801
> 331	21.9715013504
> 333	25.1646156311
> 334	26.900261879
> 335	26.8830595016
> 336	25.680398941
> 338	22.5288629532
> 339	25.0769910812
> 340	26.5090608597
> 341	26.7712163925
> 342	28.4946069717
> 343	30.6374015808
> 344	32.1122608185
> 346	36.4701061249
> 347	38.2147827148
> 348	39.4035339355
> 349	42.5643787384
> 350	43.4474239349
> 351	44.2411384583
> 352	46.4486713409
> 354	49.226140976
> 355	48.9208564758
> 356	51.4942951202
> 357	53.1595649719
> 358	52.774269104
> 359	52.8413143158
> 360	55.8098602295
> 362	57.7907295227
> 363	58.9153881073
> 364	61.1454772949
> 365	61.9867630005
> 366	61.8533439636
> 367	61.2550621033
> 368	59.5317420959
> 369	57.94190979
> 370	56.9874343872
> 371	55.5929489136
> 372	53.7092552185
> 373	52.1920318604
> 374	51.3821315765
> 375	49.6236801147
> 376	47.6341304779
> 377	46.8845329285
> 378	46.20353508
> 379	44.109872818
> 380	42.1147079468
> 381	42.1157531738
> 382	40.9585094452
> 383	38.2737979889
> 384	37.7126865387
> 385	37.6318817139
> 386	36.2848300934
> 387	33.7851333618
> 388	33.3119812012
> 389	33.4633426666
> 390	31.1289224625
> 391	29.4490032196
> 392	30.5304298401
> 393	30.1652498245
> 394	27.7359657288
> 395	27.295463562
> 396	27.5452432632
> 397	25.1247367859
> 398	24.4031791687
> 399	26.0705375671
> 400	27.8581533432
> 401	27.4462690353
> 402	28.7285032272
> 403	30.1286897659
> 404	28.7357587814
> 405	28.751200676
> 406	31.3680992126
> 407	31.0255565643
> 408	29.8933992386
> 409	31.5602741241
> 410	33.6934165955
> 412	32.2579097748
> 413	34.4666194916
> 414	35.9716205597
> 415	35.1428852081
> 416	35.9104404449
> 417	38.4630489349
> 418	39.1779575348
> 419	38.794839859
> 420	40.8995399475
> 421	42.5794506073
> 422	42.1190795898
> 423	41.6605854034
> 424	44.2788562775
> 425	45.9332256317
> 426	45.185585022
> 427	46.613117218
> 428	48.768163681
> 429	49.4665622711
> 430	50.9321975708
> 431	53.6123390198
> 432	54.6160583496
> 433	54.1917667389
> 434	55.6729354858
> 436	55.7913856506
> 437	57.8922462463
> 438	55.5628223419
> 439	52.1809329987
> 440	50.3085231781
> 441	48.1540870667
> 442	47.4776439667
> 443	46.2260169983
> 444	44.6928482056
> 445	43.3726196289
> 446	43.1298351288
> 447	41.0297222137
> 448	39.5682678223
> 449	38.821685791
> 450	36.5341148376
> 451	34.2363052368
> 452	34.341217041
> 453	33.6446037292
> 454	30.9397535324
> 455	29.8405666351
> 456	29.5383043289
> 457	27.4973716736
> 458	25.5856761932
> 459	25.7529821396
> 460	24.7552700043
> 461	22.012629509
> 462	21.956612587
> 463	23.350897789
> 464	22.0935964584
> 465	20.6458616257
> 466	20.1003875732
> 468	23.5401134491
> 469	25.4823293686
> 470	25.8739490509
> 471	23.9072322845
> 472	24.8093948364
> 473	26.931101799
> 474	26.3372335434
> 475	24.8170557022
> 476	26.8912878036
> 477	28.4003105164
> 478	27.0625476837
> 479	24.3043451309
> 480	20.331278801
> 481	19.7148170471
> 482	22.1957588196
> 483	23.7340288162
> 484	23.3155469894
> 485	24.7962942123
> 486	27.1677513123
> 487	27.8088922501
> 488	28.4261379242
> 489	30.4469881058
> 490	32.3279018402
> 491	33.0826377869
> 492	34.6080646515
> 493	36.9537239075
> 494	38.2191772461
> 495	39.0010490417
> 496	41.0129394531
> 497	43.1478691101
> 498	44.1053371429
> 499	44.7705249786
> 500	46.5488739014
Test FAILED.
```

**Comment by orbeckst** [comment]
I played with [`git bisect`](https://git-scm.com/docs/git-bisect) and isolated the commit that broke the tests: 03f39fb9bf89f7867e50910441714d9b9272dece – we need to look into it.

### How to use `git bisect`
For the record: I first created a fresh virtual env
```bash
mkvirtualenv rotcon
pip install numpy matplotlib seaborn cython biopython networkx
```
to keep everything clean.

The following script `test_install_mtssl_2011.sh` can be run on any checkout and it will install the correct packages so that tests can run (eg, correct version of MDAnalysis):
```bash
#!/bin/bash
# run script for 'git bisect': install and test for failure
# Run the PepTSO example and compare to reference result.

function die () {
    local msg="$1" err=${2:-1}
    echo "ERROR: ${msg}"
    exit $err
}


topdir="$(git rev-parse --show-toplevel)" || die "Failed to get rootdir" 125
cd "${topdir}" || die "Failed to get to the git root dir ${rootdir}" 125

# ugly hack to determine version...
VERSION=$(sed -n '/RELEASE/s/.*= *"\([^"][^"]*\)"/\1/p' setup.py)
echo "II detected rotcon VERSION=${VERSION} from setup.py"

echo "=== installation ==="
pip uninstall --yes scipy
pip uninstall --yes MDAnalysis
pip uninstall --yes RotamerConvolveMD

case "$VERSION" in
    1.0*|1.1*)
	pip install MDAnalysis==0.10.0 scipy==0.18.0;;
    1.2*)
	pip install MDAnalysis==0.11.0 scipy;;
esac
pip install . || die "Failed 'pip install .' (rotcon)" 125


echo "=== testing ==="
WDIR=doc/example

cd $WDIR || die "Failed to cd $WDIR" 125

for TESTRUNNER in test_mtssl_2011.sh test_mtssl.sh; do
    if [ -e $TESTRUNNER ]; then
	break
    fi
    TESTRUNNER=""
done
test -n "$TESTRUNNER" || die "Cannot find TESTRUNNER script" 125
echo "II Using TESTRUNNER=${TESTRUNNER}"


TMPFILE=$(mktemp -t test_mtssl_bisect) || die "Failed to create tempfile [$?]" 125
$TESTRUNNER 2>&1 | tee $TMPFILE

grep -q "diff: dat/peptso-xrd-47-330.dat: No such file or directory" $TMPFILE && die "SCRIPT FAILURE (skip bisect)" 125
grep -q "Test PASSED" $TMPFILE; rc=$?
rm -f $TMPFILE

test $rc -eq 0 && echo "Test PASSED [${rc}]" || echo "Test FAILED [${rc}]"

exit $rc
```

Then start bisecting:
```bash
git checkout master
git bisect start
git bisect bad       # the last commit is definitely broken 
git bisect good   release-1.1  # this one still tests ok
git bisect run test_install_mtssl_2011.sh
```

This reports
```
03f39fb9bf89f7867e50910441714d9b9272dece is the first bad commit
commit 03f39fb9bf89f7867e50910441714d9b9272dece
Author: Katrin Reichel <katrin.reichel@gmail.com>
Date:   Thu Jun 30 15:38:27 2016 +0200

    Changed README and adapted the distances (electron)

:100644 100644 1342e964129c22d9aabfdff3d83e1fc2825de4f6 2eb69decc8c8cd279a0f81cbbe5d9ef9ccf99388 M	README.rst
:040000 040000 6258a8e5265ac507fec5cbc5f6ff31e673b7c93b 0128e7bd3d5231395f0794ed4eb636b140642ed6 M	rotcon
bisect run success
```

and the history of what `git bisect` did can be obtained with
```bash
git bisect log
```
and gives
```
git bisect start
# bad: [e8ec143861ad4487aca266ec6d11761aff60a517] rotcon.library (not used): updated with new library file names
git bisect bad e8ec143861ad4487aca266ec6d11761aff60a517
# good: [4ace8790738cde130405726d8866dd24453afa12] release 1.1: updated links to new site on GitHub
git bisect good 4ace8790738cde130405726d8866dd24453afa12
# bad: [03f39fb9bf89f7867e50910441714d9b9272dece] Changed README and adapted the distances (electron)
git bisect bad 03f39fb9bf89f7867e50910441714d9b9272dece
# skip: [f16b4bcfa00102cba01b080b4918258b2acbbcfa] Additional output files (raw distances)
git bisect skip f16b4bcfa00102cba01b080b4918258b2acbbcfa
# good: [7c02ce7d23ff1e4b54365717997eb34153eaebfd] Update of new output options
git bisect good 7c02ce7d23ff1e4b54365717997eb34153eaebfd
# good: [0bc1c4cadd876328bf285ae2fbf9946e67322c00] bumped release number to 1.2.1.dev
git bisect good 0bc1c4cadd876328bf285ae2fbf9946e67322c00
# good: [a37a6d92ee390d0812bfebd0a1f2bfc1eb9325dc] Updated README in example folder
git bisect good a37a6d92ee390d0812bfebd0a1f2bfc1eb9325dc
# good: [4cf03399ac0500448c09a957cad44f01838156d7] bumped release to 1.3.0.dev and added docs for PRE (from #12)
git bisect good 4cf03399ac0500448c09a957cad44f01838156d7
# good: [0b76c707a97442eedf70d7e3c5f07e31529aa563] link to AUTHORS in README and init docs (closes #13)
git bisect good 0b76c707a97442eedf70d7e3c5f07e31529aa563
# first bad commit: [03f39fb9bf89f7867e50910441714d9b9272dece] Changed README and adapted the distances (electron)
```

EDIT:
- updated test script: skip bisect if I cannot figure out how to install properly (or maybe commit is inherently broken)
- updated bad commit and history (with updated script)
- updated test script (just find test_mtssl)
- updated bad commit and history (with updated script)

**Comment by orbeckst** [comment]
Maybe it is _not_  b9fbbe2; looking closely this fails for different reasons:
```
Traceback (most recent call last):
  File "/Users/oliver/.virtualenvs/rotcon/bin/convolve-mtss-rotamers.py", line 90, in <module>
    histogramBins=options.histogramBins)
  File "/Users/oliver/.virtualenvs/rotcon/lib/python2.7/site-packages/rotcon/convolve.py", line 117, in __init__
    with MDAnalysis.Writer("sit1.pdb", rotamersSite1.n_atoms) as S1:
AttributeError: 'Universe' object has no attribute 'n_atoms'
```

**Comment by orbeckst** [comment]
It is unlikely that 4cf0339 itself is responsible for the broken test because there are no code changes. The one thing that does change is that the version is bumped to 1.3.0-dev and in the tests script, this version change allows installation of the latest release of MDAnalysis. Thus, it looks likely that these changes are related to something in MDAnalysis.

The next step would be to try out all compatible versions of MDAnalysis and check at which one the tests in this commit start failing.

**Comment by orbeckst** [comment]
Manually running the test script on 03f39fb  fails:
```
=== testing ===
II Using TESTRUNNER=test_mtssl.sh
MDAnalysis  : INFO     MDAnalysis 0.16.2 STARTED logging to 'MDAnalysis.log'
MDAnalysis.app: INFO     Rotamer Convolve MD, release 1.3.0.dev --- Copyright (c) Philip W Fowler, Oliver Beckstein 2011-2013 and see AUTHORS
MDAnalysis.app: INFO     Released under the GNU Public Licence, version 2 (or higher)
MDAnalysis.app: INFO     Please cite: LS Stelzl, PW Fowler, MSP Sansom, O Beckstein. J Mol Biol 426 (2014), 735-751, doi:10.1016/j.jmb.2013.10.024
MDAnalysis.app: INFO     Loading trajectory data as Universe(peptso.gro)
MDAnalysis.app: INFO     Using rotamer library 'MTSSL 298K' by Gunnar Jeschke
MDAnalysis.app: INFO     Please cite: Polyhach Y, Bordignon E, Jeschke G. Phys Chem Chem Phys. 2011; 13(6):2356-2366. doi: 10.1039/c0cp01865a
MDAnalysis.app: INFO     Starting rotamer distance analysis of trajectory peptso.gro...
MDAnalysis.app: INFO     clashDistance = 2.2 A; rotamer library = 'MTSSL 298K'
Step     1/1 [100.0%]
/Users/oliver/.virtualenvs/rotcon/lib/python2.7/site-packages/MDAnalysis/lib/log.py:266: DeprecationWarning: Keyword *quiet* is deprecated (from version 0.16); use *verbose* instead.
  "use *{}* instead.".format(was, now), DeprecationWarning)
MDAnalysis.app: INFO     Distance distribution for residues 47 - 330 was written to dat/peptso-xrd-47-330.dat
MDAnalysis.app: INFO     DONE with analysis, elapsed time      1 s
MDAnalysis.app: INFO     Plotted distance distribution to dat/peptso-xrd.pdf
MDAnalysis  : INFO     MDAnalysis STOPPED logging
13,40c13,40
<  12.50 0.000e+00
<  13.50 1.035e-04
<  14.50 1.994e-04
<  15.50 6.309e-05
<  16.50 1.050e-03
<  17.50 1.740e-03
<  18.50 6.182e-03
<  19.50 6.770e-03
<  20.50 7.714e-03
<  21.50 7.668e-03
<  22.50 1.887e-02
<  23.50 2.775e-02
<  24.50 4.865e-02
<  25.50 6.154e-02
<  26.50 4.318e-02
<  27.50 6.543e-02
<  28.50 9.281e-02
<  29.50 8.986e-02
<  30.50 1.188e-01
<  31.50 8.475e-02
<  32.50 8.552e-02
<  33.50 7.689e-02
<  34.50 6.426e-02
<  35.50 6.220e-02
<  36.50 1.670e-02
<  37.50 1.127e-02
<  38.50 0.000e+00
<  39.50 0.000e+00
---
>  12.50 1.035e-04
>  13.50 1.994e-04
>  14.50 6.309e-05
>  15.50 7.709e-04
>  16.50 9.198e-04
>  17.50 2.554e-03
>  18.50 6.332e-03
>  19.50 6.144e-03
>  20.50 6.524e-03
>  21.50 8.692e-03
>  22.50 2.094e-02
>  23.50 3.841e-02
>  24.50 3.635e-02
>  25.50 5.834e-02
>  26.50 4.457e-02
>  27.50 4.932e-02
>  28.50 8.508e-02
>  29.50 7.847e-02
>  30.50 1.025e-01
>  31.50 9.241e-02
>  32.50 7.836e-02
>  33.50 6.997e-02
>  34.50 7.196e-02
>  35.50 5.205e-02
>  36.50 6.082e-02
>  37.50 1.370e-02
>  38.50 1.378e-02
>  39.50 6.595e-04
Test FAILED.
Test FAILED [1]
```

Manually running `test_mtssl.sh` (with the installed MDA 0.16.2): also fails.

Installing MDAnalysis 0.11.0: also fails.

**Comment by orbeckst** [comment]
@katrinr , the commit 03f39fb contains code changes in the distance calculation. Can you please have a closer look at it? The difference in the test results appear to originate here. We need to know if this is a bug or if the commit fixed a bug (and we need to change the test cases).

**Comment by katrinr** [comment]
@orbeckst, I checked the code/commit and the difference comes from using either only the N-to-N distances or N0-to-N0 distances and from that, which flag is defined or not. Just minor changes in the definition of the distances or the extension of the allowed short distances (e.g. O of MTSSL to N of residue+1) would let the test fail. I think, the test scripts are for the users to know (1) if the installation works and (2) how a run is performed and the result looks like. I think, we can just update the test files with our current settings (--useNOelectron). mh... I hope this if fine

I just updated to test files, but I think it is a bit confusing with four test scripts and in total 8 different combinations including different electron defintions and two libraries. What do you think of providing only two test scripts (as it was before): test_mtssl_deer.sh and  test_mtssl_pre.sh. People would just run their scripts (because they have either deer or pre data) with the 2015 library (as this is also the default one on MMM) and then take the flags and change by themselves after reading the documentation.

**Comment by orbeckst** [comment]
The test scripts should test all functionality of the library. I'd say, there's not such a thing as too many tests. Once the tests pass again I'd like to run these tests automatically *whenever new code is added* and *on each new PR* – that's called continuous integration (issue #23) and we use it on *every* project in MDAnalysis except this one... so to maintain quality standards, we also need CI here. 

For scientific software it is not good if the behavior changes between releases without the user knowing. At a minimum this needs to be documented (and it was bad that we didn't notice it – one more reason for CI, because we would know right away when automatic tests are failing). 

I don't really know the intricacies of RotamerConvolveMD and @philipwfowler also said as much in #22, so you, @katrinr, are pretty much in charge here.  If you say that the new way to compute the histograms is ok then I am fine with recalculating the reference data for the failing tests and adapt them as the new reference. In this case I would ask that 

1. you prepare figures that show in one plot old and new and 
2. we include these plots with a note that the behavior changed in commit 03f39fb  and 
3. you write a paragraph for this note that describes 
    - exactly what was changed
    - scientific rationale for the change

This is the responsible thing to do for users and for anyone who might want to use the library to reproduce older data from published papers. We don't want to contribute to the "reproducibility crisis" and we want to be transparent.

I agree that having all the test scripts is messy. Instead, we should write proper Python unit tests that simply run the appropriate functions such as
```python
        R = rotcon.convolve.RotamerDistances(proteinStructure,
                                             options.residues,
                                             outputFile=options.outputFile,
                                             outputFileRawDistances=options.outputFileRawDistances,
                                             dcdFilename=options.dcdFilename,
                                             dcdFilenameNoClashes=options.dcdFilenameNoClashes,
                                             libname=options.libname,
                                             discardFrames=options.discardFrames,
                                             clashDistance=options.clashDistance,
                                             histogramBins=options.histogramBins,
                                             useNOelectron=options.useNOelectron)
```
with appropriate options. One can then essentially loop over the different options and check the output for correctness.  In [MDAnalysisTests](https://github.com/MDAnalysis/mdanalysis/tree/develop/testsuite/MDAnalysisTests) we're using [pytest](https://docs.pytest.org/).

We would then only keep one or two of the "test" scripts and just use them as examples, as originally intended.

However, the first step would be to make the tests pass again (either by changing the reference or by changing the code back to old behavior).

**Comment by katrinr** [comment]
Ok :) @orbeckst, I will do what you are asking for. For the time being, I updated the test files already  and in the future I would prepare unit tests. Unfortunately, I will defend my PhD work soon and I am quite under pressure right now. I will do all the aspects including the plots and notes. Where would be the notes written (in which file)?

**Comment by orbeckst** [comment]
Defending a PhD is a good thing, not an unfortunate one ;-). 

Add files under docs as you see fit. Imagine where someone else would look. We can always link it and integrate it into the other docs later. As long as there is some content it is fine. 

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by orbeckst** [comment]
With @katrinr updates I'll close the issue.
